remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Time is of the e-scent: Time Relationships in Food.com
description: Dsc80 final project by Eric Gan